@CityInfo.API_HostAddress = https://localhost:7068

GET {{CityInfo.API_HostAddress}}/weatherforecast/
Accept: application/json

###

@cityId=0
@pointOfInterestId=0
GET {{CityInfo.API_HostAddress}}/api/v{version:apiVersion}/cities/{{cityId}}/pointsofinterest/{{pointOfInterestId}}

###
